// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRADL_bjYkaKVt0etWliG8wiLmVucY5gM',
    appId: '1:457801079777:web:b2e1bec2107d43159810a0',
    messagingSenderId: '457801079777',
    projectId: 'ecommerceapp-660c2',
    authDomain: 'ecommerceapp-660c2.firebaseapp.com',
    storageBucket: 'ecommerceapp-660c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlEuQcZC69qM98zXD_DqKjcDCPZhmRIkI',
    appId: '1:457801079777:android:6f708825855b11e19810a0',
    messagingSenderId: '457801079777',
    projectId: 'ecommerceapp-660c2',
    storageBucket: 'ecommerceapp-660c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi1to9Tc9XcZq-UM7bH2XuNNjCp1hqY40',
    appId: '1:457801079777:ios:be66cb6d09742f379810a0',
    messagingSenderId: '457801079777',
    projectId: 'ecommerceapp-660c2',
    storageBucket: 'ecommerceapp-660c2.appspot.com',
    androidClientId: '457801079777-niqkst3sn87fat6tggu3sggbvc1dt1t8.apps.googleusercontent.com',
    iosClientId: '457801079777-in7vtrj07s1mgc97p7o65if06ui3dlcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalaKari',
  );

}